Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,6 +7,10 @@ on:
     branches:
       - main
 
+env:
+  image_name: chatgpt-nodejs-app
+  dockerhub_repo: ${{ secrets.DOCKER_USERNAME }}/chatgpt-nodejs-app
+
 jobs:
   test-and-analyze:
     runs-on: ubuntu-latest
@@ -60,7 +64,44 @@ jobs:
           docker build -t chatgpt-nodejs-app:latest ./chatgpt-nodejs-app/app
           docker tag chatgpt-nodejs-app:latest ${{ secrets.DOCKER_USERNAME }}/chatgpt-nodejs-app:latest
 
+      - name: Scan Filesystem with Trivy
+        uses: aquasecurity/trivy-action@main
+        with:
+          scan-type: 'fs'
+          format: 'table'
+          exit-code: '1'
+          severity: 'CRITICAL'
+          output: trivy-fs.txt
+
+      - name: Scan Image with Trivy
+        uses: aquasecurity/trivy-action@main
+        with:
+          image-ref: ${{ env.dockerhub_repo }}:latest
+          format: 'table'
+          exit-code: '1'
+          severity: 'CRITICAL'
+          output: trivy-image.txt
+
+      - name: Upload Trivy Scan Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: trivy-scan-report
+          path: |
+            trivy-image.txt
+            trivy-fs.txt
+
+      - name: Smoke Test container
+        run: |
+          docker run -d -p 3000:3000 --name chatgpt-nodejs-app-test ${{ env.dockerhub_repo }}:latest
+          for i in {1..20}; do
+            if curl -fsS http://13.218.90.229:3000/health; then echo "OK"; exit 0; fi
+            sleep 1
+          done
+          echo "Smoke test failed" && docker logs smoketest && exit 1          
+          docker logs chatgpt-nodejs-app-test
+          docker stop chatgpt-nodejs-app-test
+          docker rm chatgpt-nodejs-app-test
+
       - name: Push Image to DockerHub
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/chatgpt-nodejs-app:latest
-    
